### ISSUE TITLE
Does FT6x36 support gestures?

### ISSUE THREAD

**Issue by FrankX0** [focaltech-systems/drivers-input-touchscreen-FTS_driver#1]
The documentation of the FT6x36 suggests it supports gestures.
However the GEST_ID register of an FT6236 is always 0.
The documentation further states that it supports "single point and gesture" and "two points".
As I can detect two points, need I change the operation mode, and if so, how?

**Comment by se2raman** [comment]
Hi Frank,

Did you got it resolved? I am facing the same issue with FT5x26.

**Comment by FrankX0** [comment]
Unfortunately not.
It seems that the (default?) firmware in the touch controller does not support gestures.

**Comment by mpaperno** [comment]
I've reluctantly come to the same conclusion, barring any evidence to the contrary.  I read the driver code here and it seems to read from some mysterious `0xD3` register to get gestures. On our FT6236 this doesn't seem like any real/relevant data at all, nor does it ever change, nor is this register documented anywhere I can see.   I've tried setting the various gesture values (radians, offsets, distances), though I have no idea what the values really mean. The documented GEST_ID is always zero.  👎

**Comment by arjunsalariya** [comment]
Hi guys,

i have facing same issue for enable gesture support with FT5436. i can't enable/set D0H(FTS_REG_GESTURE_EN) register it readback(00h) and also not get any output on D3h(FTS_REG_GESTURE_ADDRESS) register it readback(00h) always.

Did you got it resolved?

Thanks,
Arjun

**Comment by FrankX0** [comment]
I just gave up. The default firmware does not appear to support gestures.
